CREATE DATABASE yeticave
	DEFAULT CHARACTER SET utf8
	DEFAULT COLLATE utf8_general_ci;
 
 
USE yeticave;


CREATE TABLE categories(
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE lots(
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	winner_id INT NULL,
	category_id INT NOT NULL,
	create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	title VARCHAR(255) NOT NULL UNIQUE,
	description VARCHAR(255) NOT NULL,
  image VARCHAR(255) NOT NULL,
	price INT NOT NULL,
	end_time TIMESTAMP NOT NULL,
  increment_rate INT NOT NULL
);

CREATE TABLE rates(
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	lot_id INT NOT NULL,
	amount INT NOT NULL,
	create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);

CREATE INDEX user_id_idx ON rates(user_id);
CREATE INDEX lot_id_idx ON rstes(lot_id);

CREATE TABLE users(
	id INT AUTO_INCREMENT PRIMARY KEY,
	lot_id INT NOT NULL,
	create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	email VARCHAR(320) NOT NULL UNIQUE,
	name VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
  avatar VARCHAR(255) NOT NULL
);


	
